-- Generated by Oracle SQL Developer Data Modeler 4.0.0.825
--   at:        2014-08-04 11:25:56 MST
--   site:      SQL Server 2008
--   type:      SQL Server 2008




CREATE
  TABLE Address
  (
    AddressId    INTEGER NOT NULL ,
    AddressLine1 VARCHAR (100) ,
    AddressLine2 VARCHAR (100) ,
    ArchiveDate  DATETIME ,
    CityId       INTEGER NOT NULL ,
    Version      VARCHAR (30) NOT NULL ,
    ZIPCode      VARCHAR (10) ,
    CONSTRAINT AddressPK PRIMARY KEY CLUSTERED (AddressId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Attribute
  (
    AttributeId        INTEGER NOT NULL ,
    ArchiveDate        DATETIME ,
    AdditionalComments VARCHAR (2000) ,
    AttributeDefId     INTEGER NOT NULL ,
    AttributeSeq       INTEGER NOT NULL ,
    AttributeValue     VARCHAR (2000) ,
    CreatedByPersonId  INTEGER NOT NULL ,
    EntityId           INTEGER NOT NULL ,
    Version            VARCHAR (30) NOT NULL ,
    CONSTRAINT AttributePK PRIMARY KEY CLUSTERED (AttributeId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Attribute__IDX ON Attribute
(
  EntityId ,
  AttributeSeq
)
ON "default"
GO
CREATE NONCLUSTERED INDEX
Attribute__IDX ON Attribute
(
  AttributeDefId
)
ON "default"
GO

CREATE
  TABLE AttributeDef
  (
    AttributeDefId          INTEGER NOT NULL ,
    ArchiveDate             DATETIME ,
    AttributeDefName        VARCHAR (30) NOT NULL ,
    AttributeDefType        VARCHAR (3) NOT NULL ,
    AutomaticallyCreateFlag VARCHAR (1) NOT NULL ,
    DataType                VARCHAR (10) NOT NULL ,
    EntityTypeId            INTEGER ,
    MaxOccurrences          INTEGER NOT NULL ,
    OrgId                   INTEGER NOT NULL ,
    RequiredFlag            VARCHAR (1) NOT NULL ,
    ValueListId             INTEGER ,
    Version                 VARCHAR (30) NOT NULL ,
    CONSTRAINT AttributeDefPK PRIMARY KEY CLUSTERED (AttributeDefId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
AttributeDef__IDX ON AttributeDef
(
  OrgId ,
  AttributeDefType ,
  AttributeDefName
)
ON "default"
GO

CREATE
  TABLE City
  (
    CityId      INTEGER NOT NULL ,
    ArchiveDate DATETIME ,
    CityName    VARCHAR (100) NOT NULL ,
    StateId     INTEGER NOT NULL ,
    Version     VARCHAR (30) NOT NULL ,
    CONSTRAINT CityPK PRIMARY KEY CLUSTERED (CityId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
City__IDX ON City
(
  StateId ,
  CityName
)
ON "default"
GO

CREATE
  TABLE DBAudit
  (
    DBAuditId   INTEGER NOT NULL ,
    AuditAction VARCHAR (1) NOT NULL ,
    AuditDate   DATETIME NOT NULL ,
    NewData TEXT ,
    OldData TEXT ,
    OrgId    INTEGER NOT NULL ,
    PersonId INTEGER NOT NULL ,
    Version  VARCHAR (30) NOT NULL ,
    CONSTRAINT DBAuditPK PRIMARY KEY CLUSTERED (DBAuditId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE NONCLUSTERED INDEX
DBAudit__IDX ON DBAudit
(
  OrgId ,
  AuditDate
)
ON "default"
GO

CREATE
  TABLE DBUpdateNote
  (
    DBUpdateNoteId  INTEGER NOT NULL ,
    AppliedDateTime DATETIME ,
    DBRevNumber     VARCHAR (30) NOT NULL ,
    DBUpdateDesc    VARCHAR (2000) NOT NULL ,
    DevDateTime     DATETIME NOT NULL ,
    Version         VARCHAR (30) NOT NULL ,
    CONSTRAINT DBUpdateNotePK PRIMARY KEY CLUSTERED (DBUpdateNoteId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
DBUpdateNote__IDX ON DBUpdateNote
(
  DBRevNumber
)
ON "default"
GO

CREATE
  TABLE FosterHistory
  (
    FosterHistoryId  INTEGER NOT NULL ,
    ArchiveDate      DATETIME ,
    FosterDateFinish DATE ,
    FosterDateStart  DATE NOT NULL ,
    LocId            INTEGER NOT NULL ,
    OrgId            INTEGER NOT NULL ,
    PetId            INTEGER NOT NULL ,
    PrimaryPersonId  INTEGER NOT NULL ,
    Version          VARCHAR (30) NOT NULL ,
    CONSTRAINT FosterHistoryPK PRIMARY KEY CLUSTERED (FosterHistoryId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
FosterHistory__IDX ON FosterHistory
(
  PetId ,
  FosterDateStart ,
  LocId
)
ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
FosterHistory__IDX ON FosterHistory
(
  LocId ,
  FosterDateStart ,
  PetId
)
ON "default"
GO

CREATE
  TABLE Loc
  (
    LocId        INTEGER NOT NULL ,
    AddressId    INTEGER ,
    ArchiveDate  DATETIME ,
    LocDesc      VARCHAR (100) ,
    LocShortDesc VARCHAR (30) NOT NULL ,
    LocTypeId    INTEGER NOT NULL ,
    OrgId        INTEGER NOT NULL ,
    Version      VARCHAR (30) NOT NULL ,
    CONSTRAINT FosterLocPK PRIMARY KEY CLUSTERED (LocId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Loc__IDX ON Loc
(
  OrgId ,
  LocShortDesc
)
ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Loc__IDX ON Loc
(
  OrgId ,
  LocDesc
)
ON "default"
GO

CREATE
  TABLE LocPerson
  (
    LocPersonId INTEGER NOT NULL ,
    ArchiveDate DATETIME ,
    LocId       INTEGER NOT NULL ,
    OrgId       INTEGER NOT NULL ,
    PersonId    INTEGER NOT NULL ,
    PrimaryFlag VARCHAR (1) NOT NULL ,
    Version     VARCHAR (30) NOT NULL ,
    CONSTRAINT FosterLocPersonPK PRIMARY KEY CLUSTERED (LocPersonId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
LocPerson__IDX ON LocPerson
(
  PersonId ,
  LocId
)
ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
LocPerson__IDX ON LocPerson
(
  LocId ,
  PersonId
)
ON "default"
GO

CREATE
  TABLE LocType
  (
    LocTypeId        INTEGER NOT NULL ,
    ArchiveDate      DATETIME ,
    LocTypeDesc      VARCHAR (50) NOT NULL ,
    LocTypeShortDesc VARCHAR (10) NOT NULL ,
    OrgId            INTEGER NOT NULL ,
    Version          VARCHAR (30) NOT NULL ,
    CONSTRAINT FosterLocTypePK PRIMARY KEY CLUSTERED (LocTypeId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
LocType__IDX ON LocType
(
  OrgId ,
  LocTypeShortDesc
)
ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
LocType__IDX ON LocType
(
  OrgId ,
  LocTypeDesc
)
ON "default"
GO

CREATE
  TABLE NextId
  (
    NextId      INTEGER NOT NULL ,
    NextIdName  VARCHAR (30) NOT NULL ,
    NextIdValue INTEGER NOT NULL ,
    TableName   VARCHAR (30) ,
    Version     VARCHAR (30) NOT NULL ,
    CONSTRAINT NextIdPK PRIMARY KEY CLUSTERED (NextId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
NextId__IDX ON NextId
(
  NextIdName
)
ON "default"
GO

CREATE
  TABLE Org
  (
    OrgId       INTEGER NOT NULL ,
    ArchiveDate DATETIME ,
    OrgDesc     VARCHAR (200) NOT NULL ,
    OrgName     VARCHAR (50) NOT NULL ,
    Version     VARCHAR (30) NOT NULL ,
    CONSTRAINT OrgPK PRIMARY KEY CLUSTERED (OrgId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Org__IDX ON Org
(
  OrgName
)
ON "default"
GO

CREATE
  TABLE OrgPerson
  (
    OrgPersonId  INTEGER NOT NULL ,
    ArchiveDate  DATETIME ,
    OrgId        INTEGER NOT NULL ,
    PersonId     INTEGER NOT NULL ,
    PersonRoleId INTEGER NOT NULL ,
    Version      VARCHAR (30) NOT NULL ,
    CONSTRAINT OrgPersonPK PRIMARY KEY CLUSTERED (OrgPersonId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
OrgPerson__IDX ON OrgPerson
(
  OrgId ,
  PersonId
)
ON "default"
GO
CREATE NONCLUSTERED INDEX
OrgPerson__IDX ON OrgPerson
(
  PersonId ,
  OrgId
)
ON "default"
GO

CREATE
  TABLE Person
  (
    PersonId          INTEGER NOT NULL ,
    ArchiveDate       DATETIME ,
    CurrentOrgId      INTEGER ,
    DateOfBirth       DATE ,
    DisplayName       VARCHAR (50) NOT NULL ,
    EmailAddress      VARCHAR (100) ,
    FirstName         VARCHAR (30) NOT NULL ,
    LastName          VARCHAR (30) NOT NULL ,
    LoginName         VARCHAR (100) ,
    PasswordHash      VARCHAR (200) ,
    PhoneNumberHome   VARCHAR (50) ,
    PhoneNumberMobile VARCHAR (50) ,
    PhoneNumberOffice VARCHAR (50) ,
    Version           VARCHAR (30) NOT NULL ,
    CONSTRAINT PersonPK PRIMARY KEY CLUSTERED (PersonId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Person__IDX ON Person
(
  LoginName
)
ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Person__IDX ON Person
(
  DisplayName
)
ON "default"
GO

CREATE
  TABLE PersonRelationship
  (
    PersonRelationshipId INTEGER NOT NULL ,
    ArchiveDate          DATETIME ,
    PersonId1            INTEGER NOT NULL ,
    PersonId2            INTEGER NOT NULL ,
    RelationshipOf1To2   VARCHAR (20) NOT NULL ,
    RelationshipOf2To1   VARCHAR (20) NOT NULL ,
    Version              VARCHAR (30) NOT NULL ,
    CONSTRAINT PersonRelationshipPK PRIMARY KEY CLUSTERED (PersonRelationshipId
    )
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
PersonRelationship__IDX ON PersonRelationship
(
  PersonId1 ,
  PersonId2
)
ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
PersonRelationship__IDX ON PersonRelationship
(
  PersonId2 ,
  PersonId1
)
ON "default"
GO

CREATE
  TABLE PersonRole
  (
    PersonRoleId  INTEGER NOT NULL ,
    ArchiveDate   DATETIME ,
    RoleDesc      VARCHAR (30) NOT NULL ,
    RoleShortDesc VARCHAR (10) NOT NULL ,
    Version       VARCHAR (30) NOT NULL ,
    CONSTRAINT PersonRolePK PRIMARY KEY CLUSTERED (PersonRoleId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
PersonRole__IDX ON PersonRole
(
  RoleShortDesc
)
ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
PersonRole__IDX ON PersonRole
(
  RoleDesc
)
ON "default"
GO

CREATE
  TABLE Pet
  (
    PetId       INTEGER NOT NULL ,
    AdoptionFee DECIMAL (19,4) NOT NULL ,
    ArchiveDate DATETIME ,
    DateOfBirth DATE NOT NULL ,
    IntakeDate  DATE NOT NULL ,
    OrgId       INTEGER NOT NULL ,
    PetName     VARCHAR (50) NOT NULL ,
    PetTypeId   INTEGER NOT NULL ,
    Sex         VARCHAR (1) NOT NULL ,
    Version     VARCHAR (30) NOT NULL ,
    CONSTRAINT PetPK PRIMARY KEY CLUSTERED (PetId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE NONCLUSTERED INDEX
Pet__IDX ON Pet
(
  OrgId ,
  IntakeDate
)
ON "default"
GO
CREATE NONCLUSTERED INDEX
Pet__IDX ON Pet
(
  OrgId ,
  PetName
)
ON "default"
GO

CREATE
  TABLE PetType
  (
    PetTypeId        INTEGER NOT NULL ,
    ArchiveDate      DATETIME ,
    OrgId            INTEGER NOT NULL ,
    PetTypeDesc      VARCHAR (50) NOT NULL ,
    PetTypeShortDesc VARCHAR (10) NOT NULL ,
    Version          VARCHAR (30) NOT NULL ,
    CONSTRAINT FosterLocTypePK PRIMARY KEY CLUSTERED (PetTypeId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
PetType__IDX ON PetType
(
  OrgId ,
  PetTypeShortDesc
)
ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
PetType__IDX ON PetType
(
  OrgId ,
  PetTypeDesc
)
ON "default"
GO

CREATE
  TABLE PlanEntry
  (
    PlanEntryId     INTEGER NOT NULL ,
    ActionDate      DATETIME ,
    ArchiveDate     DATETIME ,
    LocId           INTEGER ,
    PetId           INTEGER NOT NULL ,
    PlanEntryNotes  VARCHAR (2000) ,
    ScheduledDate   DATETIME ,
    TreatmentTypeId INTEGER ,
    Version         VARCHAR (30) NOT NULL ,
    CONSTRAINT PetPlanPK PRIMARY KEY CLUSTERED (PlanEntryId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE NONCLUSTERED INDEX
PlanEntry__IDX ON PlanEntry
(
  PetId ,
  ScheduledDate
)
ON "default"
GO

CREATE
  TABLE PlanPerson
  (
    PlanPersonId INTEGER NOT NULL ,
    ArchiveDate  DATETIME ,
    Notes        VARCHAR (2000) ,
    PersonId     INTEGER NOT NULL ,
    PlanEntryId  INTEGER NOT NULL ,
    ReminderType VARCHAR (10) NOT NULL ,
    Version      VARCHAR (30) NOT NULL ,
    CONSTRAINT PlanPersonPK PRIMARY KEY CLUSTERED (PlanPersonId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE NONCLUSTERED INDEX
PlanPerson__IDX ON PlanPerson
(
  PersonId
)
ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
PlanPerson__IDX ON PlanPerson
(
  PlanEntryId ,
  PersonId
)
ON "default"
GO

CREATE
  TABLE PlanTemplate
  (
    PlanTemplateId   INTEGER NOT NULL ,
    ArchiveDate      DATETIME ,
    OrgId            INTEGER NOT NULL ,
    PlanTemplateDesc VARCHAR (2000) ,
    PlanTemplateName VARCHAR (50) NOT NULL ,
    Version          VARCHAR (30) NOT NULL ,
    CONSTRAINT PlanTemplatePK PRIMARY KEY CLUSTERED (PlanTemplateId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
PlanTemplate__IDX ON PlanTemplate
(
  OrgId ,
  PlanTemplateName
)
ON "default"
GO

CREATE
  TABLE PlanTemplateEntry
  (
    PlanTemplateEntryId   INTEGER NOT NULL ,
    ArchiveDate           DATETIME ,
    OffsetNumberOfDays    INTEGER ,
    PlanTemplateEntryDesc VARCHAR (50) NOT NULL ,
    PlanTemplateId        INTEGER NOT NULL ,
    Version               VARCHAR (30) NOT NULL ,
    CONSTRAINT PlanTemplateEntryPK PRIMARY KEY CLUSTERED (PlanTemplateEntryId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE NONCLUSTERED INDEX
PlanTemplateEntry__IDX ON PlanTemplateEntry
(
  PlanTemplateId
)
ON "default"
GO

CREATE
  TABLE PlanTemplateTreatment
  (
    PlanTemplateTreatmentId INTEGER NOT NULL ,
    ArchiveDate             DATETIME ,
    LocId                   INTEGER ,
    PlanTemplateEntryId     INTEGER NOT NULL ,
    TreatmentTypeId         INTEGER NOT NULL ,
    Version                 VARCHAR (30) NOT NULL ,
    CONSTRAINT PlanTemplateTreatmentPK PRIMARY KEY CLUSTERED (
    PlanTemplateTreatmentId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE NONCLUSTERED INDEX
PlanTemplateTreatment__IDX ON PlanTemplateTreatment
(
  PlanTemplateEntryId
)
ON "default"
GO

CREATE
  TABLE SearchDef
  (
    SearchDefId   INTEGER NOT NULL ,
    ArchiveDate   DATETIME ,
    OrgId         INTEGER NOT NULL ,
    OwnerPersonId INTEGER NOT NULL ,
    PublicFlag    VARCHAR (1) NOT NULL ,
    SearchDefDesc VARCHAR (100) ,
    SearchDefName VARCHAR (30) ,
    SearchDefType VARCHAR (20) NOT NULL ,
    SortColumns   VARCHAR (200) ,
    Version       VARCHAR (30) NOT NULL ,
    CONSTRAINT SearchDefPK PRIMARY KEY CLUSTERED (SearchDefId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE SearchDefDetail
  (
    SearchDefDetailId INTEGER NOT NULL ,
    ArchiveDate       DATETIME ,
    SearchDefId       INTEGER NOT NULL ,
    Value1            VARCHAR (50) ,
    Value2            VARCHAR (50) ,
    Value3            VARCHAR (50) ,
    ValueList TEXT ,
    ValueName VARCHAR (50) NOT NULL ,
    Version   VARCHAR (30) NOT NULL ,
    CONSTRAINT SearchDefDetailPK PRIMARY KEY CLUSTERED (SearchDefDetailId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
SearchDefDetail__IDX ON SearchDefDetail
(
  SearchDefId ,
  ValueName
)
ON "default"
GO

CREATE
  TABLE SessionToken
  (
    SessionTokenId INTEGER NOT NULL ,
    PersonId       INTEGER NOT NULL ,
    SessionToken   VARCHAR (100) ,
    CONSTRAINT SessionTokenPK PRIMARY KEY CLUSTERED (SessionTokenId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
SessionToken_SessionToken_IDX ON SessionToken
(
  SessionToken
)
ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
SessionToken_PersonId_SessionToken_IDX ON SessionToken
(
  PersonId ,
  SessionToken
)
ON "default"
GO

CREATE
  TABLE State
  (
    StateId     INTEGER NOT NULL ,
    ArchiveDate DATETIME ,
    StateAbbrev VARCHAR (2) NOT NULL ,
    StateName   VARCHAR (50) NOT NULL ,
    Version     VARCHAR (30) NOT NULL ,
    CONSTRAINT StatePK PRIMARY KEY CLUSTERED (StateId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
State__IDX ON State
(
  StateAbbrev
)
ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
State__IDX ON State
(
  StateName
)
ON "default"
GO

CREATE
  TABLE Treatment
  (
    TreatmentId     INTEGER NOT NULL ,
    ArchiveDate     DATETIME ,
    Cost            DECIMAL (19,4) NOT NULL ,
    LocId           INTEGER NOT NULL ,
    OrgId           INTEGER NOT NULL ,
    PetId           INTEGER NOT NULL ,
    PlanEntryId     INTEGER ,
    ScheduledDate   DATETIME ,
    TreatmentDate   DATE ,
    TreatmentDesc   VARCHAR (200) ,
    TreatmentTypeId INTEGER NOT NULL ,
    Version         VARCHAR (30) NOT NULL ,
    CONSTRAINT TreatmentPK PRIMARY KEY CLUSTERED (TreatmentId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE NONCLUSTERED INDEX
Treatment__IDX ON Treatment
(
  PetId ,
  TreatmentDate
)
ON "default"
GO

CREATE
  TABLE TreatmentType
  (
    TreatmentTypeId        INTEGER NOT NULL ,
    ArchiveDate            DATETIME ,
    OrgId                  INTEGER NOT NULL ,
    TreatmentTypeDesc      VARCHAR (50) NOT NULL ,
    TreatmentTypeShortDesc VARCHAR (10) NOT NULL ,
    Version                VARCHAR (30) NOT NULL ,
    CONSTRAINT FosterLocTypePK PRIMARY KEY CLUSTERED (TreatmentTypeId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
TreatmentType__IDX ON TreatmentType
(
  OrgId ,
  TreatmentTypeShortDesc
)
ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
TreatmentType__IDX ON TreatmentType
(
  OrgId ,
  TreatmentTypeDesc
)
ON "default"
GO

CREATE
  TABLE ValueList
  (
    ValueListId   INTEGER NOT NULL ,
    ArchiveDate   DATETIME ,
    OrgId         INTEGER NOT NULL ,
    ValueListDesc VARCHAR (50) NOT NULL ,
    ValueList TEXT ,
    Version VARCHAR (30) NOT NULL ,
    CONSTRAINT ValueListPK PRIMARY KEY CLUSTERED (ValueListId)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
ValueList__IDX ON ValueList
(
  OrgId ,
  ValueListDesc
)
ON "default"
GO


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            30
-- CREATE INDEX                            43
-- ALTER TABLE                              0
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
